### ISSUE TITLE
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": plugin not available

### ISSUE THREAD

**Issue by WentangChen** [paulotto/canfnet#1]
hi 

Thank you for your excellent work! 
I want to implement your work on my digit sensor, but I have encountered some problems: 
When I use command:
roslaunch canfnet.launch rqt_gui:=true tactile_device:=DIGIT tactile_device_path:=/dev/GelSightMini \
                         digit_serial:=D20266 tactile_cam_undistort:=true torch_device:=cuda canfnet_force_filt:=true \
                         model:="$(find canfnet)/models/DIGIT/model.pth"
the terminal shows:
![2023-11-10_21-04](https://github.com/paulotto/canfnet/assets/95954901/3a6694d1-b361-479f-b7c2-4a65703d5005)

1. Can you help me with this problem?
2. Can you tell me which PyQt5 verison you use?
3. What python version do you use?

Thanks, looking forward to your reply

**Comment by WentangChen** [comment]
I have solve the above problems, but I can not receive the matplot of overall normal force, can you offer some help?
![2023-11-10_21-45](https://github.com/paulotto/canfnet/assets/95954901/8811ab5a-340d-4b5e-aa9a-bc5aca3b0988)

**Comment by paulotto** [comment]
Hi @WentangChen  ,

Thank you for your interest in our work. 

You need to select or type "/canfnet/unet_estimation/force" into the box indicated by the arrow in the image and click the plus icon.
![image1](https://github.com/paulotto/canfnet/assets/65675744/f5918225-d9f2-47ee-bf9c-7a7779ff52bd)

Best regards,
Paul
